theme: jekyll-theme-minimal

title: "Michael L. Wick"
url: https://michaelwick.github.io
logo: /files/images/me_gren.png
description:
Homepage <br/> [Google Scholar](https://scholar.google.com/citations?user=D0DpJUwAAAAJ&hl=en&oi=ao)

relative_links:
  enabled: true
  collections: true

