theme: jekyll-theme-minimal

title: "Michael L. Wick"
url: https://michaelwick.github.io
logo: /files/images/me_gren.png
description: Michael's Homepage

relative_links:
  enabled: true
  collections: true

