theme: jekyll-theme-minimal

title: "Michael L. Wick"
url: https://michaelwick.github.io
logo: /files/images/mike_grenoble_thumb.png
description: Michael's academic homepage

relative_links:
  enabled: true
  collections: true

